
export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export interface RiskFactor {
  category: string;
  score: number; // 0-100, where 100 is high risk
  finding: string;
  severity: RiskLevel;
  details: string;
}

export interface Organization {
  name: string;
  ein: string;
  fiscalYear: number;
  revenue: number;
  assets: number;
}

export interface AssessmentResult {
  organization: Organization;
  overallRiskScore: number; // 0-100
  generatedAt: string;
  factors: RiskFactor[];
  aiSummary?: string; // Generated by Gemini
}

export interface QuickCheckRequest {
  ein: string;
  email?: string;
}

// Client Portal Types
export interface User {
  id: string;
  name: string;
  email: string;
  organization: string;
  role: string;
}

export interface DashboardData {
  user: User;
  stats: {
    riskScore: number;
    openFindings: number;
    resolvedFindings: number;
    nextDeadline: string;
  };
  alerts: {
    id: number;
    type: 'critical' | 'warning' | 'info';
    message: string;
    date: string;
  }[];
  findings: {
    id: number;
    category: string;
    description: string;
    severity: RiskLevel;
    status: 'Open' | 'In Progress' | 'Resolved';
  }[];
  reports: {
    id: number;
    name: string;
    date: string;
    type: string;
    size: string;
  }[];
}
