"""initial_schema_baseline

Revision ID: 12962dcbc832
Revises: 
Create Date: 2026-01-23 17:23:30.458194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12962dcbc832'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('monthly_scan_limit', sa.Integer(), nullable=False),
    sa.Column('scans_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_table('litigation_holds',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('activated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('ai_interpretations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('interpretation_type', sa.String(), nullable=False),
    sa.Column('input_refs', sa.Text(), nullable=False),
    sa.Column('ai_output_text', sa.Text(), nullable=False),
    sa.Column('ai_model_version', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('advisory_disclaimer', sa.String(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_interpretations_id'), 'ai_interpretations', ['id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('event_payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('prev_event_hash', sa.String(), nullable=True),
    sa.Column('event_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_table('dafs',
    sa.Column('daf_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('daf_external_id', sa.String(length=100), nullable=True),
    sa.Column('sponsor_organization', sa.String(length=200), nullable=False),
    sa.Column('advisor_id', sa.String(length=100), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('daf_id')
    )
    op.create_index(op.f('ix_dafs_client_id'), 'dafs', ['client_id'], unique=False)
    op.create_index(op.f('ix_dafs_sponsor_organization'), 'dafs', ['sponsor_organization'], unique=False)
    op.create_table('export_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('export_generated_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('methodology_versions', sa.String(), nullable=True),
    sa.Column('hash_algorithm', sa.String(), nullable=True),
    sa.Column('package_hash', sa.String(), nullable=False),
    sa.Column('download_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_records_id'), 'export_records', ['id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('ein', sa.String(), nullable=True),
    sa.Column('tax_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_id'), 'ingestion_jobs', ['id'], unique=False)
    op.create_table('revenue_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('related_id', sa.String(length=36), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_revenue_events_client_id'), 'revenue_events', ['client_id'], unique=False)
    op.create_index(op.f('ix_revenue_events_event_type'), 'revenue_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_revenue_events_transaction_date'), 'revenue_events', ['transaction_date'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('score_total', sa.Integer(), nullable=True),
    sa.Column('methodology_version', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('computed_by', sa.String(), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_id'), 'risk_scores', ['id'], unique=False)
    op.create_table('abuse_reports',
    sa.Column('abuse_report_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('daf_id', sa.String(length=36), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('abuse_patterns', sa.JSON(), nullable=False),
    sa.Column('total_abuse_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('report_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_url', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['daf_id'], ['dafs.daf_id'], ),
    sa.PrimaryKeyConstraint('abuse_report_id')
    )
    op.create_index(op.f('ix_abuse_reports_client_id'), 'abuse_reports', ['client_id'], unique=False)
    op.create_index(op.f('ix_abuse_reports_daf_id'), 'abuse_reports', ['daf_id'], unique=False)
    op.create_table('scans',
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('daf_id', sa.String(length=36), nullable=True),
    sa.Column('scan_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('risks_detected', sa.Integer(), nullable=True),
    sa.Column('critical_risks', sa.Integer(), nullable=True),
    sa.Column('high_risks', sa.Integer(), nullable=True),
    sa.Column('medium_risks', sa.Integer(), nullable=True),
    sa.Column('low_risks', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_url', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['daf_id'], ['dafs.daf_id'], ),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_index(op.f('ix_scans_client_id'), 'scans', ['client_id'], unique=False)
    op.create_index(op.f('ix_scans_daf_id'), 'scans', ['daf_id'], unique=False)
    op.create_index(op.f('ix_scans_started_at'), 'scans', ['started_at'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingestion_job_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('tax_year', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_hash', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('ein', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_id'), 'source_documents', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('daf_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('vendor_id', sa.String(length=100), nullable=True),
    sa.Column('advisor_id', sa.String(length=100), nullable=True),
    sa.Column('beneficiary_id', sa.String(length=100), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['daf_id'], ['dafs.daf_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_client_id'), 'transactions', ['client_id'], unique=False)
    op.create_index(op.f('ix_transactions_daf_id'), 'transactions', ['daf_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_table('risk_detections',
    sa.Column('detection_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('violation_type', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('remediation_cost_estimate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bounty_potential', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('detection_id')
    )
    op.create_index(op.f('ix_risk_detections_client_id'), 'risk_detections', ['client_id'], unique=False)
    op.create_index(op.f('ix_risk_detections_created_at'), 'risk_detections', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_detections_risk_level'), 'risk_detections', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risk_detections_status'), 'risk_detections', ['status'], unique=False)
    op.create_index(op.f('ix_risk_detections_transaction_id'), 'risk_detections', ['transaction_id'], unique=False)
    op.create_table('remediation_cases',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('detection_id', sa.String(length=36), nullable=True),
    sa.Column('violation_type', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('violation_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_analyst', sa.String(length=36), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detection_id'], ['risk_detections.detection_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_remediation_cases_client_id'), 'remediation_cases', ['client_id'], unique=False)
    op.create_index(op.f('ix_remediation_cases_created_at'), 'remediation_cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_remediation_cases_status'), 'remediation_cases', ['status'], unique=False)
    op.create_table('whistleblower_reports',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('violation_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('estimated_bounty', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('irs_form_211_data', sa.JSON(), nullable=False),
    sa.Column('submission_status', sa.String(length=20), nullable=False),
    sa.Column('submission_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('award_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('agency_share_percentage', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['remediation_cases.case_id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_whistleblower_reports_client_id'), 'whistleblower_reports', ['client_id'], unique=False)
    op.create_index(op.f('ix_whistleblower_reports_submission_status'), 'whistleblower_reports', ['submission_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whistleblower_reports_submission_status'), table_name='whistleblower_reports')
    op.drop_index(op.f('ix_whistleblower_reports_client_id'), table_name='whistleblower_reports')
    op.drop_table('whistleblower_reports')
    op.drop_index(op.f('ix_remediation_cases_status'), table_name='remediation_cases')
    op.drop_index(op.f('ix_remediation_cases_created_at'), table_name='remediation_cases')
    op.drop_index(op.f('ix_remediation_cases_client_id'), table_name='remediation_cases')
    op.drop_table('remediation_cases')
    op.drop_index(op.f('ix_risk_detections_transaction_id'), table_name='risk_detections')
    op.drop_index(op.f('ix_risk_detections_status'), table_name='risk_detections')
    op.drop_index(op.f('ix_risk_detections_risk_level'), table_name='risk_detections')
    op.drop_index(op.f('ix_risk_detections_created_at'), table_name='risk_detections')
    op.drop_index(op.f('ix_risk_detections_client_id'), table_name='risk_detections')
    op.drop_table('risk_detections')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_daf_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_client_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_source_documents_id'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_started_at'), table_name='scans')
    op.drop_index(op.f('ix_scans_daf_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_client_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_abuse_reports_daf_id'), table_name='abuse_reports')
    op.drop_index(op.f('ix_abuse_reports_client_id'), table_name='abuse_reports')
    op.drop_table('abuse_reports')
    op.drop_index(op.f('ix_risk_scores_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_revenue_events_transaction_date'), table_name='revenue_events')
    op.drop_index(op.f('ix_revenue_events_event_type'), table_name='revenue_events')
    op.drop_index(op.f('ix_revenue_events_client_id'), table_name='revenue_events')
    op.drop_table('revenue_events')
    op.drop_index(op.f('ix_ingestion_jobs_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_export_records_id'), table_name='export_records')
    op.drop_table('export_records')
    op.drop_index(op.f('ix_dafs_sponsor_organization'), table_name='dafs')
    op.drop_index(op.f('ix_dafs_client_id'), table_name='dafs')
    op.drop_table('dafs')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_ai_interpretations_id'), table_name='ai_interpretations')
    op.drop_table('ai_interpretations')
    op.drop_table('litigation_holds')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
