
export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export interface RiskFactor {
  category: string;
  score: number; // 0-100, where 100 is high risk
  finding: string;
  severity: RiskLevel;
  details: string;
}

// Represents the data inside a 990 filing
export interface OrganizationFinancials {
  name: string;
  ein: string;
  fiscalYear: number;
  revenue: number;
  assets: number;
}

export interface AssessmentResult {
  organization: OrganizationFinancials;
  overallRiskScore: number; // 0-100
  generatedAt: string;
  factors: RiskFactor[];
  aiSummary?: string; // Generated by Gemini
  entropyScore?: {
    raw: number;
    normalized: number;
    year: number;
  };
  aiGovernance?: {
    model: string;
    version: string;
    traceId: string;
    disclaimer: string;
  };
}

export interface QuickCheckRequest {
  ein: string;
  email?: string;
}

// --- PLATFORM TYPES (MCC PHASE 2 - ENTERPRISE) ---

export enum ReportStatus {
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
}

export interface ReportArtifact {
  id: string;
  name: string;
  type: 'Audit' | 'Advisory' | 'Data' | 'Forensic' | 'Regulatory';
  status: ReportStatus;
  generatedAt: string;
  size?: string;
  url?: string;
  hash?: string; // SHA-256 for immutability
}

export interface OrganizationEntity {
  id: string;
  name: string;
  ein: string;
  riskScore: number;
  lastAssessmentDate: string;
  status: 'Active' | 'Archived' | 'Pending';
  memberCount: number;
}

export interface User {
  id: string;
  name: string;
  email: string;
  role: string;
  avatarUrl?: string;
}

// Compliance & Audit Types
export interface LitigationHold {
  id: string;
  isActive: boolean;
  reason: string;
  scope: 'GLOBAL' | 'PARTIAL';
  activatedBy: string;
  activatedAt: string;
}

export interface AuditEvent {
  id: string;
  action: string;
  actor: string;
  timestamp: string;
  metadata: any;
  hash: string;
}

export interface BenchmarkData {
  myScore: number;
  sectorMedian: number;
  sectorP75: number;
  sectorP90: number;
  percentile: number;
  position: 'HIGH_RISK_QUARTILE';
}

export interface Finding {
    id: number;
    category: string;
    description: string;
    severity: RiskLevel;
    status: 'Open' | 'In Progress' | 'Resolved';
    verificationStatus: 'AI_GENERATED' | 'HUMAN_VERIFIED' | 'FLAGGED_FOR_REVIEW';
    verifiedBy?: string;
    verifiedAt?: string;
}

export interface DashboardContext {
  currentUser: User;
  currentOrganization: OrganizationEntity;
  availableOrganizations: OrganizationEntity[];
}

export interface DashboardData {
  context: DashboardContext;
  stats: {
    riskScore: number;
    openFindings: number;
    resolvedFindings: number;
    nextDeadline: string;
  };
  alerts: {
    id: number;
    type: 'critical' | 'warning' | 'info';
    message: string;
    date: string;
  }[];
  findings: Finding[];
  reports: ReportArtifact[];
  // Compliance Extensions
  litigationHold?: LitigationHold;
  auditLog?: AuditEvent[];
  benchmark?: BenchmarkData;
  donorConcentration?: { name: string; value: number; color: string }[];
  aiGovernance: {
      modelId: string;
      modelVersion: string;
      lastAudit: string;
  };
}
